name = "cloudflare-docker-proxy"
workers_dev = true
main = "src/index.js"
compatibility_date = "2021-12-07"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.libcuda.so", custom_domain = true },
  { pattern = "quey.libcuda.so", custom_domain = true },
  { pattern = "gcr.libcuda.so", custom_domain = true },
  { pattern = "k8s-gcr.libcuda.so", custom_domain = true },
  { pattern = "k8s.libcuda.so", custom_domain = true },
  { pattern = "ghcr.libcuda.so", custom_domain = true },
  { pattern = "cloudsmith.libcuda.so", custom_domain = true },
]

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"